// Generated by CoffeeScript 1.6.3
(function() {
  var mainApp;

  mainApp = angular.module("MainApp");

  mainApp.controller('HomeCtlr', [
    '$scope', '$location', '$route', 'MainConstants', 'DemoService', function($scope, $location, $route, MainConstants, DemoService) {
      $scope.location = $location;
      $scope.route = $route;
      $scope.windowLocation = window.location;
      console.log("HomeCtlr");
      $scope.errorMsg = "";
      $scope.baseUrl = MainConstants.baseUrl;
      return true;
    }
  ]);

}).call(this);
