// Generated by CoffeeScript 1.6.3
(function() {
  var mainApp;

  mainApp = angular.module("MainApp");

  mainApp.controller('HomeCtlr', [
    '$scope', '$location', '$route', 'MetaConstants', 'DemoService', function($scope, $location, $route, MetaConstants, DemoService) {
      $scope.location = $location;
      $scope.route = $route;
      $scope.windowLocation = window.location;
      console.log("HomeCtlr");
      $scope.errorMsg = "";
      $scope.baseUrl = MetaConstants.baseUrl;
      return true;
    }
  ]);

}).call(this);
