// Generated by CoffeeScript 1.6.3
(function() {
  var mainApp;

  mainApp = angular.module("MainApp");

  mainApp.controller('TestCtlr', [
    '$scope', '$location', '$route', 'MetaConstants', 'DemoService', function($scope, $location, $route, MetaConstants, DemoService) {
      $scope.location = $location;
      $scope.route = $route;
      $scope.winLoc = window.location;
      console.log("TestCtlr");
      $scope.errorMsg = "";
      $scope.demoPromise = DemoService.call($scope, 'doit', {
        'name': 'John'
      });
      $scope.demoPromise.success(function(data, status, headers, config) {
        console.log("Demo success");
        $scope.demo = data;
        return true;
      });
      return true;
    }
  ]);

}).call(this);
