// Generated by CoffeeScript 1.6.3
(function() {
  var mainApp;

  mainApp = angular.module("MainApp", ['metaService', 'ssFilter', 'demoService']);

  mainApp.constant('MainConstants', {
    name: 'Halide',
    owner: 'SaltStack'
  });

  mainApp.config([
    "MetaConstants", "MainConstants", "$locationProvider", "$routeProvider", function(MetaConstants, MainConstants, $locationProvider, $routeProvider) {
      var base;
      $locationProvider.html5Mode(true);
      console.log("MetaConstants");
      console.log(MetaConstants);
      console.log("MainConstants");
      console.log(MainConstants);
      base = MetaConstants.baseUrl;
      $routeProvider.when("" + base + "/app/home", {
        templateUrl: "" + base + "/static/app/view/home.html",
        controller: "HomeCtlr"
      }).when("" + base + "/app/watch/:id", {
        templateUrl: "" + base + "/static/app/view/watch.html",
        controller: "WatchCtlr"
      }).when("" + base + "/app/test", {
        templateUrl: "" + base + "/static/app/view/test.html",
        controller: "TestCtlr"
      }).otherwise({
        redirectTo: "" + base + "/app/home"
      });
      return true;
    }
  ]);

  mainApp.controller('NavbarCtlr', [
    '$scope', '$location', '$route', '$routeParams', 'MetaConstants', function($scope, $location, $route, $routeParams, MetaConstants) {
      console.log("NavbarCtlr");
      $scope.location = $location;
      $scope.route = $route;
      $scope.winLoc = window.location;
      $scope.baseUrl = MetaConstants.baseUrl;
      $scope.errorMsg = '';
      $scope.views = MetaConstants.views;
      $scope.navery = {
        'navs': {},
        'activate': function(navact) {
          var label, nav, _ref;
          navact.state = 'active';
          _ref = this.navs;
          for (label in _ref) {
            nav = _ref[label];
            if (nav !== navact) {
              nav.state = 'inactive';
            }
          }
          return true;
        },
        'update': function(newPath, oldPath) {
          var label, nav, _ref;
          _ref = this.navs;
          for (label in _ref) {
            nav = _ref[label];
            if (newPath.match(nav.matcher) != null) {
              this.activate(nav);
              return true;
            }
          }
          return true;
        },
        'load': function(views) {
          var item, name, view, _results;
          _results = [];
          for (name in views) {
            item = views[name];
            if (item.label != null) {
              _results.push(this.navs[item.label] = {
                state: 'inactive',
                matcher: item.matcher
              });
            } else {
              _results.push((function() {
                var _i, _len, _results1;
                _results1 = [];
                for (_i = 0, _len = item.length; _i < _len; _i++) {
                  view = item[_i];
                  _results1.push(this.navs[view.label] = {
                    state: 'inactive',
                    matcher: view.matcher
                  });
                }
                return _results1;
              }).call(this));
            }
          }
          return _results;
        }
      };
      $scope.navery.load($scope.views);
      $scope.$watch('location.path()', function(newPath, oldPath) {
        $scope.navery.update(newPath, oldPath);
        return true;
      });
      return true;
    }
  ]);

  mainApp.controller('RouteCtlr', [
    '$scope', '$location', '$route', '$routeParams', 'MetaConstants', function($scope, $location, $route, $$routeParams, MetaConstants) {
      console.log("RouteCtlr");
      $scope.location = $location;
      $scope.route = $route;
      $scope.winLoc = window.location;
      $scope.baseUrl = MetaConstants.baseUrl;
      $scope.errorMsg = '';
      return true;
    }
  ]);

}).call(this);
