// Generated by CoffeeScript 1.6.3
(function() {
  var mainApp;

  mainApp = angular.module("MainApp", ['demoService']);

  mainApp.constant('MainConstants', {
    baseUrl: '/halide',
    owner: 'SaltStack'
  });

  mainApp.config([
    "MainConstants", "$locationProvider", "$routeProvider", function(MainConstants, $locationProvider, $routeProvider) {
      var base;
      $locationProvider.html5Mode(true);
      console.log(MainConstants);
      base = MainConstants.baseUrl;
      $routeProvider.when("" + base + "/app/home", {
        templateUrl: "" + base + "/static/app/view/home.html",
        controller: "HomeCtlr"
      }).otherwise({
        redirectTo: "" + base + "/app/home"
      });
      return true;
    }
  ]);

}).call(this);
