// Generated by CoffeeScript 1.6.3
/*
usage:
$scope.demoPromise = DemoService.call $scope, 'doit', {'name':'John'}
$scope.demoPromise.success (data, status, headers, config) ->
    console.log("Demo success")
    $scope.demo = data
    return true
*/


(function() {
  angular.module("demoService", ['metaService']).factory("DemoService", [
    '$http', 'MetaConstants', function($http, MetaConstants) {
      return {
        call: function($scope, action, query) {
          var base, url;
          base = MetaConstants.baseUrl;
          url = action != null ? "" + base + "/demo/" + action : "" + base + "/demo";
          return $http.get(url, {
            params: query
          }).success(function(data, status, headers, config) {
            console.log("DemoService " + action + " success");
            console.log(config);
            console.log(status);
            console.log(headers());
            console.log(data);
            return true;
          }).error(function(data, status, headers, config) {
            console.log("DemoService " + action + " failure");
            console.log(config);
            console.log(status);
            console.log(headers());
            console.log(data);
            $scope.errorMsg = (data != null ? data.error : void 0) || data;
            return true;
          });
        }
      };
    }
  ]);

}).call(this);
