// Generated by CoffeeScript 1.6.3
(function() {
  var base, buildRegex, metaservice, views;

  metaservice = angular.module("metaService", []);

  base = '/halide';

  views = {
    otherwise: {
      label: "home",
      route: "" + base + "/app/home",
      template: "" + base + "/static/app/view/home.html",
      controller: "HomeCtlr"
    },
    watch: {
      label: "watch",
      route: "" + base + "/app/watch/:mid",
      template: "" + base + "/static/app/view/watch.html",
      controller: "WatchCtlr"
    },
    test: {
      label: "test",
      route: "" + base + "/app/test",
      template: "" + base + "/static/app/view/test.html",
      controller: "testCtlr"
    }
  };

  buildRegex = function(url) {};

  metaservice.constant('MetaConstants', {
    baseUrl: "" + base,
    date: '20120625',
    views: views
  });

}).call(this);
