// Generated by CoffeeScript 1.6.3
(function() {
  var base, buildMatcher, matcherify, metaservice, views;

  metaservice = angular.module("metaService", []);

  base = '/halide';

  views = {
    otherwise: {
      label: "home",
      route: "" + base + "/app/home",
      url: "" + base + "/app/home",
      template: "" + base + "/static/app/view/home.html",
      controller: "HomeCtlr"
    },
    tabs: [
      {
        label: "watch",
        route: "" + base + "/app/watch/:id",
        url: "" + base + "/app/watch/",
        template: "" + base + "/static/app/view/watch.html",
        controller: "WatchCtlr"
      }, {
        label: "test",
        route: "" + base + "/app/test",
        url: "" + base + "/app/test",
        template: "" + base + "/static/app/view/test.html",
        controller: "testCtlr"
      }
    ]
  };

  buildMatcher = function(route) {
    var chunk, chunks, i, matcher, _i, _len;
    chunks = route.split("/");
    for (i = _i = 0, _len = chunks.length; _i < _len; i = ++_i) {
      chunk = chunks[i];
      if (chunk.match("^:\\w+$") != null) {
        chunks[i] = "\\w*";
      }
    }
    matcher = "^" + chunks.join("/") + "$";
    return matcher;
  };

  matcherify = function(views) {
    var item, name, view, _i, _len;
    for (name in views) {
      item = views[name];
      if (item.label != null) {
        item.matcher = buildMatcher(item.route);
      } else {
        for (_i = 0, _len = item.length; _i < _len; _i++) {
          view = item[_i];
          view.matcher = buildMatcher(view.route);
        }
      }
    }
    return views;
  };

  matcherify(views);

  metaservice.constant('MetaConstants', {
    baseUrl: "" + base,
    date: '20120625',
    views: views
  });

}).call(this);
